version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - lab-network

  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - lab-network
    depends_on:
      - redis

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - lab-network
    depends_on:
      - service-discovery
      - redis

  applicationmanagementservice:
    build:
      context: ./RecruitmentManagement/ApplicationManagementService
      dockerfile: Dockerfile
    ports:
      - "5096:80"
    networks:
      - lab-network
    depends_on:
      - api-gateway
      - applicationmanagementdb

  jobmanagementservice:
    build:
      context: ./RecruitmentManagement/JobManagementService
      dockerfile: Dockerfile
    ports:
      - "5062:80"
    networks:
      - lab-network
    depends_on:
      - api-gateway
      - jobmanagementdb

  applicationmanagementdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: applicationmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - applicationmanagement-data:/var/lib/postgresql/data
    networks:
      - lab-network

  jobmanagementdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: jobmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - jobmanagement-data:/var/lib/postgresql/data
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge

volumes:
  applicationmanagement-data:
  jobmanagement-data: