{
 "title": "MetricDashboard_1",
 "description": "MetricDashboard_1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Service Get Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "applications_get_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "applications_get_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Up Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HostingTotalRequest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_total_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api_Gateway_Get_Post",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "applications_get_total", "legendFormat": "__auto" },
    { "expr": "applications_post_total", "legendFormat": "__auto" }
   ]
  }
 ]
}