apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-management-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-management-service
  template:
    metadata:
      labels:
        app: application-management-service
    spec:
      containers:
        - name: application-management-service
          image: applicationmanagementservice
          ports:
            - containerPort: 7200
---
kind: Service
apiVersion: v1
metadata:
  name: application-management-service
spec:
  selector:
    app: application-management-service
  ports:
    - protocol: TCP
      port: 7200
  type: LoadBalancer
