global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-discovery'
    static_configs:
      - targets: ['service-discovery:4000']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3001']

  - job_name: 'applicationmanagementservice1'
    static_configs:
      - targets: ['applicationmanagementservice1:80']

  - job_name: 'jobmanagementservice1'
    static_configs:
      - targets: ['jobmanagementservice1:80']
