apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-management-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-management-service
  template:
    metadata:
      labels:
        app: job-management-service
    spec:
      containers:
        - name: job-management-service
          image: jobmanagementservice
          ports:
            - containerPort: 7160
---
kind: Service
apiVersion: v1
metadata:
  name: job-management-service
spec:
  selector:
    app: job-management-service
  ports:
    - protocol: TCP
      port: 7160
  type: LoadBalancer
